# Generated by Django 4.2.5 on 2023-09-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_alter_carro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='imagem',
            field=models.ImageField(default=1, upload_to='logo_marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(upload_to='imagem_carro'),
        ),
        migrations.AddField(
            model_name='marca',
            name='continente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.continente'),
        ),
    ]
