# Generated by Django 4.2.5 on 2023-09-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_alter_continente_nome_alter_marca_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='pais',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
