# Generated by Django 4.2.5 on 2023-09-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_marca_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='imagem',
            field=models.ImageField(default=1, upload_to='img_continentes'),
            preserve_default=False,
        ),
    ]
