# Generated by Django 4.2.5 on 2023-09-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_continente_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
