# Generated by Django 4.2.5 on 2023-12-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0008_marca_url_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='url_video',
        ),
    ]
