# Generated by Django 4.2.5 on 2023-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0009_remove_marca_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='url_video',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
