# Generated by Django 4.2.5 on 2024-03-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0010_carro_url_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='continente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nome']},
        ),
    ]
